name: my-rdkit-env
channels:
  - rdkit
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py37h2bbff1b_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.10.0=pyh06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.4=py37h080aedc_0
  - ca-certificates=2022.4.26=haa95532_0
  - cairo=1.14.12=hf171d8a_3
  - certifi=2022.6.15=py37haa95532_0
  - cffi=1.15.0=py37h2bbff1b_1
  - colorama=0.4.4=pyhd3eb1b0_0
  - debugpy=1.5.1=py37hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py37haa95532_0
  - freetype=2.10.4=hd328e21_0
  - icu=58.2=ha925a31_3
  - importlib-metadata=4.11.3=py37haa95532_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.9.1=py37haa95532_0
  - ipython=7.31.1=py37haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py37haa95532_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jpeg=9d=h2bbff1b_0
  - jsonschema=4.4.0=py37haa95532_0
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_core=4.9.2=py37haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - libboost=1.67.0=hd9e427e_4
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.2.0=hd0e1b90_0
  - libwebp=1.2.2=h2bbff1b_0
  - lz4-c=1.9.3=h2bbff1b_1
  - markupsafe=2.0.1=py37h2bbff1b_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py37hfa6e2cd_1001
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.1=py37h277e83a_0
  - mkl_random=1.2.2=py37hf11a4ad_0
  - nb_conda_kernels=2.3.1=py37haa95532_0
  - nbclient=0.5.11=pyhd3eb1b0_0
  - nbconvert=6.4.4=py37haa95532_0
  - nbformat=5.3.0=py37haa95532_0
  - nest-asyncio=1.5.5=py37haa95532_0
  - notebook=6.4.8=py37haa95532_0
  - numexpr=2.8.1=py37hb80d3ca_0
  - numpy=1.21.5=py37h7a0a035_1
  - numpy-base=1.21.5=py37hca35cd5_1
  - openssl=1.1.1o=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.5=py37h6214cd6_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py37hdc2b20a_0
  - pip=21.2.4=py37haa95532_0
  - pixman=0.40.0=h2bbff1b_1
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - py-boost=1.67.0=py37h8300f20_4
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyrsistent=0.18.0=py37h196d8e1_0
  - python=3.7.13=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python_abi=3.7=2_cp37m
  - pytz=2021.3=pyhd3eb1b0_0
  - pywin32=302=py37h827c3e9_1
  - pywinpty=2.0.2=py37h5da7b33_0
  - pyzmq=22.3.0=py37hd77b12b_2
  - rdkit=2020.09.1.0=py37h3d1ada6_1
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py37haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.2=h2bbff1b_0
  - terminado=0.13.1=py37haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.11=h2bbff1b_0
  - tornado=6.1=py37h2bbff1b_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py37haa95532_2
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.12=h8cc25b3_1
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - charset-normalizer==2.0.12
    - idna==3.3
    - requests==2.27.1
    - urllib3==1.26.9
prefix: C:\Miniconda\envs\my-rdkit-env
